### ISSUE TITLE
Static attributes

### ISSUE THREAD

**Issue by erithmetic** [faradayio/carbon#1]
Allow:

```
provide :segments_per_trip, :with => 1
```

Saying that that property will always be assigned a value of 1

**Comment by seamusabshere** [comment]
after working on mastercard for a while, i found that i liked just plain methods like

```
def segments_per_trip
  1
end
```

but i'm assigning to @rossmeissl for opinionation

**Comment by rossmeissl** [comment]
@dkastner, why not

``` ruby
provide 1, :as => :segments_per_trip
```

?
